
export const DOG_BREEDS = [
  'Golden Retriever',
  'Labrador Retriever',
  'German Shepherd',
  'French Bulldog',
  'Poodle',
  'Shih Tzu',
  'Corgi',
  'Pomeranian',
  'Husky',
  'Chihuahua',
  'Maltese',
  'Yorkshire Terrier',
  'Dachshund',
  'Samoyed',
  'Border Collie',
  'Australian Shepherd',
  'Cavalier King Charles Spaniel',
  'Bichon Frise',
  'Bernedoodle',
  'Goldendoodle',
  'Miniature Schnauzer',
  'Schnauzer',
]